name : ReleaseBuild
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  #リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOULUTION_FILE_PATH: projects/YKEngine.sln
  #Visual Studio の構成(Debud / Release )
  CONFIGURATION: Release
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          msbuild ${{env.SOULUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
